# Generated by Django 6.0.1 on 2026-02-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=40)),
                ('Content', models.TextField(max_length=400)),
                ('Phone_Number', models.IntegerField(max_length=15)),
            ],
        ),
    ]
